config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  resources :temperature_criteria
  resources :temperatures
  devise_for :users, :path => 'u'
  resources :users do
    collection do
      get 'change_state'
    end
  end

  # root "temperature_criteria#index"
  root "notifications#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <%= render 'layouts/navigation_links' %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<ul class="nav navbar-nav navbar-left">
  <li><%= link_to 'Temperatures', temperature_criteria_path %></li>
  <li><%= link_to 'Enable Notification', change_state_users_path(status: :start) %></li>
  <li><%= link_to 'Disable Notification', change_state_users_path(status: :stop) %></li>
  <li id="notifications"> </li>
</ul>
<ul class="nav navbar-nav navbar-right">   
    <% if user_signed_in? %>   
    <li><%= link_to current_user.email, edit_user_registration_path %></li>   
    <li><%= link_to "Log Out" , destroy_user_session_path, method: :delete %></li>   
    <% else %>   
    <li><%= link_to "Sign In", user_session_path %></li>   
    <li><%= link_to "Register", new_user_registration_path %></li>   
    <% end %>   
 </ul> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TemperatureApp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "TemperatureApp" %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container-fluid">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>